name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 32.236.227.110
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: ./deploy.sh
      